baseURL = "https://weddingpresent.netlify.com/"
languageCode = "en-us"
title = "Weddingpresent"
theme=""
summaryLength = "7"

# Menu
[menu]
	
	[[menu.nav]]
    name = "Home"
    URL = "hero-area"
    weight = 1

    [[menu.nav]]
    name = "About Us"
    URL = "about-us"
    weight = 2

    [[menu.nav]]
    name = "Blog"
    URL = "blog"
    weight = 3

    [[menu.nav]]
    name = "Price"
    URL = "price"
    weight = 4

    [[menu.nav]]
    name = "News"
    URL = "subscribe"
    weight = 5

    [[menu.nav]]
    name = "Contact Us"
    URL = "contact-us"
    weight = 6



# Global Settings
[params]
logo = "images/logo.png"


[params.heroArea]
enable = true
[params.heroImg ] 
url =  "images/header.jpg" 


#gallery item

[params.gallery]
enable = true
title= "Location <span>Review</span>"

[[params.gallery.item]]
img = "images/slider/slide-01.jpg"

[[params.gallery.item]]
img = "images/slider/slide-02.jpg"

[[params.gallery.item]]
img = "images/slider/slide-03.jpg"

[[params.gallery.item]]
img = "images/slider/slide-04.jpg"

[[params.gallery.item]]
img = "images/slider/slide-05.jpg"

[[params.gallery.item]]
img = "images/slider/slide-06.jpg"

[[params.gallery.item]]
img = "images/slider/slide-07.jpg"


[params.about]
enable = true
title= "True <span>Love</span> stories never have endings."
bgImage = "images/cooker-img.png"
description= "Your wedding day is the most memorable of your life. To help make it so, entrust your ceremony and reception to our team of highly professional and caring wedding planners at Pathumwan Princess Hotel. Our Best Wedding Package, with its a wide choice of menus and venues, offers exceptional value for money, with the hotel providing luxurious facilities, highly attentive service and a convenient location to ensure un-stressful travel for guests."




#food Menu

[params.foodMenu]
enable = true
title = "Our Easy <span>PRICE</span>"
description= " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco"
subtitle = "FEATURED ON THE WEEK"

[[params.foodMenu.item]]
title="Pancakes n' Such Titas"
description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim&&"
price = "$ 125.00"

[[params.foodMenu.item]]
title="Caesar Salad"
description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim&&"
price = "$ 100.00"

[[params.foodMenu.item]]
title="Steak with a Garlic and Parsley Risotto"
description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim&&"
price = "$ 20.00"

[[params.foodMenu.item]]
title="Meat of Skewers"
description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim&&"
price = "$ 45.00"

[[params.foodMenu.item]]
title="Pancakes n' Such"
description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim&&"
price = "$ 25.00"



#subscription

[params.subscription]
enable = true
title= "SUBSCRIBE to our <span>NEWSLETTER</span>"
description = ""

#Mailchimp subscription configaration 
formAction = "https://themefisher.us9.list-manage.com/subscribe/post?u=f95ece2732a6e9925f2e70a61&amp;id=b1e227529e"
formName = "b_f95ece2732a6e9925f2e70a61_b1e227529e"

#Contact 

[params.contact]
enable = true
title= "our <span> Contact Us </span>"
subtitle= "SIGN UP FOR EMAIL ALERTS"
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod"


#Footer 

[params.footer]
enable = true
contactInfoTitle = "CONTACT <span>INFO</span> "
blogTitle = "LATEST <span>UPDATE</span>"
galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "Follow <span>US</span>"

[[params.footer.contactItem]]
title="Telephone"
icon = "fa fa-phone"
content = "07985 25987"

[[params.footer.contactItem]]
title="Address"
icon = "fa fa-map-marker"
content = "80/2 Khatu Phuket 83120"

[[params.footer.contactItem]]
title="E mail"
icon = "fa fa-envelope"
content = "weddingpresent@gmail.com"

[[params.footer.socialLink]]
icon = "facebook"
link = "https://fb.com/themefisher"


[[params.footer.socialLink]]
icon = "twitter"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "dribbble"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://fb.com/themefisher"


#Footer Copyright

#Footer Copyright Text
[params.footerCopyright]
enable = true
Text = "Copyright 2019 - All Rights Wedding Present and Developed By N4S and Theme by Themefisher.com"




#blog 
[params.blog]
enable = true
title = "Wedding <span> Services </span> for <span>you</span>"
